server:
  port: 8885
  address: 0.0.0.0
  servlet:
    context-path: /account-service

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.168.240:3306/tcc_account?useUnicode=true&characterEncoding=utf8
    username: root
    password: HUANGfu0110..
  application:
    name: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled : false
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能

mybatis:
  configuration:
    map-underscore-to-camel-case: true


account-service :
  ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: info
    org.dromara.hmily.bonuspoint: debug
    org.dromara.hmily.lottery: debug
    org.dromara.hmily: debug
    io.netty: info
  path: "./logs"