server:
  port: 8884
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.168.240:3306/tcc_order?useUnicode=true&characterEncoding=utf8
    username: root
    password: HUANGfu0110..
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#Ribbon的负载均衡策略
hmilyOrder :
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
    MaxAutoRetriesNextServer : 0

feign:
  hystrix:
    enabled : true
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能

mybatis:
  configuration:
    map-underscore-to-camel-case: true

hmily:
  ribbon:
    rule:
      enabled: true

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: info
    org.dromara.hmily.bonuspoint: debug
    org.dromara.hmily.lottery: debug
    org.dromara.hmily: debug
    io.netty: info
  path: "./logs"