server:
  port: 8761

spring:
  application:
    name: springcloud-eureka
eureka:
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60
